name: 🐞 버그 제보
description: 발견한 버그나 오류를 보고합니다.
title: "[BUG] "
labels: ["bug"]
assignees: [] # 필요 시 기본 담당자 입력

body:
  - type: textarea
    id: overview
    attributes:
      label: 📌 개요
      description: 버그에 대한 간략한 설명을 작성해주세요.
      placeholder: ex) 로그인 시 500 Internal Server Error 발생
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 재현 절차
      description: 버그를 재현하기 위한 상세한 절차를 작성해주세요.
      placeholder: |
        1. 로그인 페이지로 이동
        2. 이메일과 비밀번호 입력
        3. 로그인 버튼 클릭
        4. 오류 발생
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 💡 기대 동작
      description: 정상적으로 동작해야 하는 모습을 작성해주세요.
      placeholder: ex) 정상적으로 대시보드 페이지로 이동
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 🛠 실제 동작
      description: 실제로 발생한 결과를 작성해주세요.
      placeholder: ex) 500 Internal Server Error 페이지로 이동
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥 환경 정보
      description: 버그가 발생한 환경 정보를 작성해주세요.
      placeholder: |
        - OS: Windows 11
        - 브라우저: Chrome 120.0
        - Backend 버전: v1.0.0
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: ✅ 체크리스트
      description: 이슈 처리 완료를 확인하는 항목을 작성해주세요.
      placeholder: |
        - [ ] 로컬 환경에서 버그 재현 확인
        - [ ] 원인 분석 완료
        - [ ] 수정 코드 배포
        - [ ] QA 테스트 완료
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 📚 참고
      description: 관련 로그, 스크린샷, 이슈 번호 등을 기재해주세요.
      placeholder: |
        - 관련 로그 파일
        - #23
    validations:
      required: false
