spring:
  datasource:
    url: jdbc:mysql://localhost:3306/visionary
    username: root
    password: user1234!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
