spring:
  application:
    name: visionary
# 기본 활성 프로필
  profiles:
    default: local

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate   # 스키마는 Flyway로 관리, JPA는 검증만
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:           # Actuator
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,threaddump,httpexchanges
  endpoint:
    health:
      show-details: when_authorized

jwt:
  issuer: "visionary"
  access-token-expiration-ms: 1800000     # 30분
  refresh-token-expiration-ms: 604800000  # 7일
  access-token-header: "Authorization"
  refresh-token-cookie: "Refresh-Token"
  secret: "${JWT_SECRET}"  # 환경변수로 덮어쓰기

firebase:
  # 아래 둘 중 하나를 사용 (권장: 환경변수 GOOGLE_APPLICATION_CREDENTIALS)
  use-google-default-credentials: true
  service-account-json-path: "${FIREBASE_CREDENTIALS_PATH:}"  # ex) file:/etc/secret/firebase.json

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info  # 파라미터 로깅(개발 중에만 올리기)
