name: 🔧 Chore 작업
description: 패키지 구조 변경, 설정 수정, 빌드 환경 변경 등 유지보수 작업을 기록합니다.
title: "[Chore] "
labels: ["chore"]
assignees: [] # 필요 시 기본 담당자 입력

body:
  - type: textarea
    id: overview
    attributes:
      label: 📌 개요
      description: 작업에 대한 간략한 설명을 작성해주세요.
      placeholder: ex) 프로젝트 패키지 구조를 리팩토링하여 유지보수성과 확장성을 향상시킵니다.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 💡 변경 사유
      description: 변경이 필요한 이유를 구체적으로 작성해주세요.
      placeholder: |
        - 기존 패키지 구조가 모듈 간 의존성이 높아 관리가 어려움
        - 기능별/도메인별 구분이 명확하지 않아 코드 탐색 시간 증가
        - 신규 기능 추가 시 구조적인 제약 발생
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 🛠 변경 사항
      description: 작업에서 수행한 주요 변경 사항을 작성해주세요.
      placeholder: |
        - 패키지를 도메인 중심으로 재구성 (user, auth, file, common 등)
        - 공통 유틸, 설정, 예외 처리를 global/common 패키지로 이동
        - API 엔드포인트와 서비스, 레포지토리 계층 구조 명확화
        - 테스트 코드 경로 패키지 구조와 맞춤
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: ✅ 체크리스트
      description: 이슈 처리 완료를 확인하는 항목을 작성해주세요.
      placeholder: |
        - [ ] 로컬 환경에서 버그 재현 확인
        - [ ] 원인 분석 완료
        - [ ] 수정 코드 배포
        - [ ] QA 테스트 완료
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 📚 참고
      description: 관련 문서나 참고 자료를 기재해주세요.
      placeholder: |
        - Clean Architecture, DDD(Domain-Driven Design) 패턴 참고
        - 팀 내 패키지 구조 컨벤션 문서
    validations:
      required: false
